### ISSUE TITLE
Install on CentOS6

### ISSUE THREAD

**Issue by gerhard-tinned** [claudijd/ssh_scan#43]
I tried to install it on CentOS 6.

$ gem install bindata
Successfully installed bindata-2.2.0
1 gem installed
Installing ri documentation for bindata-2.2.0...
Installing RDoc documentation for bindata-2.2.0...

$ ./bin/ssh_scan --target host.domain.tld --port 22 --policy policies/mozilla_intermediate.yml
./bin/../lib/ssh_scan.rb:2:in `require': no such file to load -- bindata (LoadError)
        from ./bin/../lib/ssh_scan.rb:2
        from ./bin/ssh_scan:6:in `require'
        from ./bin/ssh_scan:6

Anny idea what is missing here?

**Comment by gerhard-tinned** [comment]
$ gem list

*** LOCAL GEMS ***

bindata (2.2.0)

**Comment by claudijd** [comment]
@gerhard-tinned I'm looking into it now.  Can you also provide the output for "ruby -v" and "which ruby"?

Prime suspects:
1.) Old Ruby version that need RubyGems required to load an external lib
2.) Some weird path setting magic happening

Please let me know and I'll do my best to sort that out soon.

**Comment by claudijd** [comment]
I tried replicating this on Ubuntu first, to save time, and found a 1.9.3 compatibility bug which I fixed in #44 

It's probably unrelated to the bug you're seeing, but is a decent sign that there may be compatibility issues in the 1.9.x branch I still need to sort out.  Something to note here is that 1.9.x went EOL a couple days ago, but I will make attempts to provide some backwards compatibility.  If you're running on 1.8.x,  it's been EOL for a while now and you should consider upgrading.

I will continue to dig in once I build a CentOS 6 test target.  Thanks!

**Comment by claudijd** [comment]
Looks like in CentOS 6.7, the latest Ruby version available via the package manager is Ruby 1.8.7, which is long deprecated (~June 2013).

In order for this even function on CentOS 6.7 on Ruby 1.8.x, you would need to do the following (untested):
1.) yum install ruby
2.) yum install rubygems
3.) add 'require "rubygems"' to the top of ./lib/ssh_scan.rb

From a practical perspective, you're probably better off by simply upgrading your Ruby version to something more modern (1.9.x at the least, but it would be better to be in the 2.x branch).  You can install Ruby from source using the following instructions:

http://ask.xmodulo.com/upgrade-ruby-centos.html

You could also upgrade to a newer version of CentOS, which may provide a newer Ruby by default or via the package manager.

**Comment by claudijd** [comment]
Ok, so in digging into this further, it appears that modern BinData has a minimum requirement of at least 1.9.3.

If you are intent on working around this and sticking with Ruby 1.8, you'll need the following:

1.) yum groupinstall 'Development Tools'  #get development tools for JSON compiling, which isn't part Ruby 1.8 by default
2.) yum install ruby
3.) yum install rubygems
4.) gem uninstall bindata #remove the latest bindata, which is only compatible with 1.9.3 and greater
5.) gem install bindata -v '~> 1.8.0' # install an old bindata version, which works for 1.8.x ruby
6.) yum install ruby-devel # to help with JSON compiling
7.) gem install json # because it wasn't bundled with Ruby until 1.9.x

You will notice some slightly odd behavior when looking at results run in this way because hashes in ruby weren't always ordered.  It will still run scans, but the order of the JSON elements could be out of order because hashes are not ordered.

I was able to confirm this works, but considering all the hoops you have to go through to make it happen, you're probably better off just upgrading your ruby version as I recommend above.  After seeing what a mess this is, I'm going to make a call right now that I'll be supporting 1.9.x for a short period of time (which is now EOL) and providing full support for 2.x.  I will not provide any further support for 1.8, which is certainly showing it's age.

**Comment by claudijd** [comment]
Also, I happened to realize that I had a supported rubies list on the README.md...

https://github.com/claudijd/ssh_scan#rubies-supported

**Comment by gerhard-tinned** [comment]
Sorry for the late answer ... You are right all the way as it seems. 

$ ruby -v
ruby 1.8.7 (2013-06-27 patchlevel 374) [i386-linux]

I have a old ruby version. I will try to upgrade ...

**Comment by claudijd** [comment]
@gerhard-tinned thanks for confirming.  If it was something else, I would have been worried.  Let me know if you have any future problems, I'd be glad to help get you up and running if you're stuck.
